#!/usr/bin/env bash
# BlackBelt v2 — Domain & SSL Setup Guide
# This script documents the steps needed. Run manually as appropriate.

set -euo pipefail

echo "=== BlackBelt v2 — Domain Setup Guide ==="
echo ""
echo "STEP 1: DNS Configuration (at your DNS provider, e.g. Cloudflare)"
echo "  Add the following DNS records:"
echo ""
echo "  CNAME  yourdomain.com      → cname.vercel-dns.com"
echo "  CNAME  www                  → cname.vercel-dns.com"
echo ""
echo "STEP 2: Vercel Domain Configuration"
echo "  vercel domains add yourdomain.com"
echo "  vercel domains add www.yourdomain.com"
echo "  SSL is automatically provisioned by Vercel."
echo ""
echo "STEP 3: Set Environment Variables in Vercel"
echo "  vercel env add NEXT_PUBLIC_APP_URL             # https://yourdomain.com"
echo "  vercel env add NEXT_PUBLIC_SUPABASE_URL        # https://xxx.supabase.co"
echo "  vercel env add NEXT_PUBLIC_SUPABASE_ANON_KEY   # your anon key"
echo "  vercel env add SUPABASE_SERVICE_ROLE_KEY       # your service role key"
echo "  vercel env add NEXT_PUBLIC_USE_MOCK            # false"
echo "  vercel env add PAYMENT_GATEWAY                 # asaas or stripe"
echo "  vercel env add ASAAS_API_KEY                   # your API key"
echo "  vercel env add ASAAS_WEBHOOK_TOKEN             # your webhook token"
echo "  vercel env add RESEND_API_KEY                  # your Resend key"
echo "  vercel env add NEXT_PUBLIC_SENTRY_DSN          # your Sentry DSN"
echo "  vercel env add SENTRY_AUTH_TOKEN               # your Sentry token"
echo ""
echo "STEP 4: Configure Payment Webhook"
echo "  In your payment gateway dashboard, set webhook URL to:"
echo "  https://yourdomain.com/api/webhooks/payment"
echo "  Events: payment.confirmed, payment.overdue, subscription.*"
echo ""
echo "STEP 5: Configure Email (Resend)"
echo "  1. Verify your domain at resend.com (add DNS records: SPF, DKIM, DMARC)"
echo "  2. Set FROM address: noreply@yourdomain.com"
echo ""
echo "STEP 6: Redeploy"
echo "  git push origin main   # Vercel auto-deploys"
echo "  Or: vercel --prod"
echo ""
echo "STEP 7: Verify"
echo "  curl https://yourdomain.com/api/health"
echo "  Expected: {\"status\":\"healthy\",...}"
